"""Template Markdown artifacts per TaskKind. See docs/architecture.md §4.3."""

from datetime import UTC, datetime

from app.models.enums import ArtifactType, TaskKind
from app.runtimes.base import ProducedArtifact, TaskContext


def _header(ctx: TaskContext) -> str:
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    return (
        f"> Task: {ctx.title} (#EID-{ctx.task_id})  \n"
        f"> Author: {ctx.employee_name} ({ctx.employee_role})  \n"
        f"> Generated: {now} by MockRuntime\n\n"
    )


def _prd(ctx: TaskContext) -> ProducedArtifact:
    content = (
        f"# PRD: {ctx.title}\n\n"
        + _header(ctx)
        + "## 1. Background\n\n"
        + (ctx.description or "（原始需求见任务描述）")
        + "\n\n## 2. Goals\n\n"
        + "- 满足订单描述中的核心诉求\n- 交付物可被 QA 验证\n\n"
        + "## 3. Scope\n\n### In Scope\n- 核心功能实现\n- 单元测试\n\n"
        + "### Out of Scope\n- 运维与部署自动化\n\n"
        + "## 4. Acceptance Criteria\n\n"
        + (ctx.acceptance_criteria or "- 功能按描述工作\n- 测试全部通过\n")
    )
    return ProducedArtifact(ArtifactType.prd.value, f"PRD: {ctx.title}", content)


def _research_report(ctx: TaskContext) -> ProducedArtifact:
    content = (
        f"# Research Report: {ctx.title}\n\n"
        + _header(ctx)
        + "## Summary\n\n对需求相关技术方案进行了调研，给出推荐选型。\n\n"
        + "## Findings\n\n"
        + "- 方案 A：实现简单，生态成熟，适合 MVP。\n"
        + "- 方案 B：扩展性强，但引入额外复杂度，暂缓。\n\n"
        + "## Recommendation\n\n采用方案 A，后续按需评估方案 B。\n\n"
        + "## Sources\n\n"
        + "- https://example.com/docs/option-a\n"
        + "- https://example.com/benchmarks/a-vs-b\n"
        + "- internal://knowledge/mvp-constraints\n"
    )
    return ProducedArtifact(ArtifactType.research_report.value, f"Research: {ctx.title}", content)


def _source_code(ctx: TaskContext) -> ProducedArtifact:
    content = (
        f"# Implementation: {ctx.title}\n\n"
        + _header(ctx)
        + "## Architecture\n\n"
        + "单一模块 + 清晰函数边界；入口 `main()`，核心逻辑在 `run()`，便于测试。\n\n"
        + "## Code\n\n```python\n"
        + '"""Auto-generated by MockRuntime."""\n\n\n'
        + "def run() -> list[str]:\n"
        + '    """Core domain logic."""\n'
        + "    items: list[str] = []\n"
        + "    return items\n\n\n"
        + "def main() -> None:\n"
        + "    for item in run():\n"
        + "        print(item)\n\n\n"
        + 'if __name__ == "__main__":\n'
        + "    main()\n"
        + "```\n\n## Notes\n\n- 无外部依赖，Python 3.11+ 即可运行。\n"
    )
    return ProducedArtifact(ArtifactType.source_code.value, f"Code: {ctx.title}", content)


def _test_report(ctx: TaskContext) -> ProducedArtifact:
    content = (
        f"# Test Report: {ctx.title}\n\n"
        + _header(ctx)
        + "## Result: PASS\n\n"
        + "| Suite | Tests | Passed | Failed |\n|---|---|---|---|\n"
        + "| unit | 12 | 12 | 0 |\n| integration | 3 | 3 | 0 |\n\n"
        + "## Coverage\n\n- core logic: 96%\n\n## Verdict\n\n满足验收标准，建议进入最终评审。\n"
    )
    return ProducedArtifact(ArtifactType.test_report.value, f"Test Report: {ctx.title}", content)


def _approval(ctx: TaskContext) -> ProducedArtifact:
    content = (
        f"# Order Review: {ctx.title}\n\n"
        + _header(ctx)
        + "## Decision: APPROVED\n\n需求清晰、范围可控，批准进入规划阶段。\n"
    )
    return ProducedArtifact(ArtifactType.plan.value, f"Order Review: {ctx.title}", content)


def _release(ctx: TaskContext) -> ProducedArtifact:
    content = (
        f"# Release: {ctx.title}\n\n"
        + _header(ctx)
        + "## Decision: SHIP\n\n"
        + "所有里程碑完成，测试通过，批准发布。\n\n"
        + "## Release Notes\n\n- 核心功能交付\n- 测试全部通过\n"
    )
    return ProducedArtifact(ArtifactType.release.value, f"Release: {ctx.title}", content)


def _general(ctx: TaskContext) -> ProducedArtifact:
    content = f"# Output: {ctx.title}\n\n" + _header(ctx) + "任务已完成。\n"
    return ProducedArtifact(ArtifactType.other.value, f"Output: {ctx.title}", content)


_BUILDERS = {
    TaskKind.planning.value: _prd,
    TaskKind.research.value: _research_report,
    TaskKind.development.value: _source_code,
    TaskKind.testing.value: _test_report,
    TaskKind.order_review.value: _approval,
    TaskKind.final_review.value: _release,
    TaskKind.general.value: _general,
}


def build_artifact(ctx: TaskContext, behavior: str = "") -> ProducedArtifact:
    """behavior：由 app.brain.projection.behavior_block() 渲染好的投影块（调用方不做判断）。"""
    artifact = _BUILDERS.get(ctx.kind, _general)(ctx)
    if behavior:
        # §3.4 验收条件 2/4：投影必须能在产出里被机器验证到。
        artifact.content += f"\n\n## Behavior Projection\n\n{behavior}\n"
    if ctx.prior_knowledge:
        # Make learning retrieval observable in the produced artifact.
        skills = "\n".join(f"- {name}" for name in ctx.validated_skills) or "- (none validated yet)"
        topics = "\n".join(f"- {topic}" for topic in ctx.prior_knowledge)
        artifact.content += (
            "\n\n## Prior Knowledge Applied\n\n"
            f"using prior knowledge:\n{topics}\n\n## Validated Skills\n\n{skills}\n"
        )
    return artifact


def role_message(ctx: TaskContext) -> str:
    lines = {
        TaskKind.order_review.value: "审阅订单需求，评估可行性并给出审批意见。",
        TaskKind.planning.value: "拆解需求，撰写 PRD 并规划里程碑。",
        TaskKind.research.value: "调研相关技术方案，输出调研报告。",
        TaskKind.development.value: "依据 PRD 与调研结论进行开发实现。",
        TaskKind.testing.value: "依据验收标准设计并执行测试。",
        TaskKind.final_review.value: "终审交付物，决定是否发布。",
        TaskKind.general.value: "处理通用任务。",
    }
    return f"{ctx.employee_name}（{ctx.employee_role}）：{lines.get(ctx.kind, lines['general'])}"
