"""v39 npc economic profiles

Revision ID: 64fec2d13d9b
Revises: 862e2d3d7d8e
Create Date: 2026-09-11 15:41:10.832682

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "64fec2d13d9b"
down_revision = "862e2d3d7d8e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "npc_economic_profiles",
        sa.Column("participant_id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("budget_cap", sa.Integer(), nullable=False),
        sa.Column("budget_injected_total", sa.Integer(), nullable=False),
        sa.Column("max_price", sa.Integer(), nullable=False),
        sa.Column("fit_threshold_bps", sa.Integer(), nullable=False),
        sa.Column("deals_per_round", sa.Integer(), nullable=False),
        sa.Column("policy_version", sa.String(length=40), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["market_participants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("participant_id", name="uq_npc_profile_participant"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("npc_economic_profiles")
    # ### end Alembic commands ###
