"""v38 talent commercial terms

Revision ID: 862e2d3d7d8e
Revises: 0425abecc96e
Create Date: 2026-09-11 15:30:41.463287

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "862e2d3d7d8e"
down_revision = "0425abecc96e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talent_commercial_terms',
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('seller_company_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=12), nullable=False),
    sa.Column('sale_mode', sa.String(length=16), nullable=False),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['market_listings.id'], ),
    sa.ForeignKeyConstraint(['seller_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', name='uq_talent_terms_listing')
    )
    op.create_index(
        "ix_talent_terms_seller", "talent_commercial_terms", ["seller_company_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_talent_terms_seller", table_name="talent_commercial_terms")
    op.drop_table('talent_commercial_terms')
    # ### end Alembic commands ###
